import * as express from 'express';
import * as bodyParser from 'body-parser';
import * as functions from 'firebase-functions';
import { initDb } from './db';

const swaggerUI = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');
const routes = require('./routes');

const main = express();

initDb();

const options = {
  swaggerDefinition: {
    info: {
      title: 'Field Set API',
      version: '1.0.0',
      description: 'API for the Field Set App with autogenerated swagger documentation.'
    },
    basePath: '/api/v1',
  },
  basePath: '/api/v1',
  apis: ['**/*.ts']
}
const specs = swaggerJsdoc(options);

main.use('/docs', swaggerUI.serve, swaggerUI.setup(specs));
// main.use(bodyParser.json());
main.use(bodyParser.urlencoded({ extended: false }));
main.use('/v1', routes);

// // webApi is your functions name, and you will pass main as
// // a parameter
export const api = functions.https.onRequest(main);
